### ISSUE TITLE
Linux dedicated app support?

### ISSUE THREAD

**Issue by arduinka55055** [google/nearby-connections#25]
It will be nice, if you will add some dedicated application for GNU/Linux (maybe you also add this feature for windows ) that will run in daemon mode. So if you start sharing something to laptop, you will get popup and you can accept file.

So you can transfer files without chrome opened

**Comment by kavanmevada** [comment]
I can make GTK app. I'm trying to figure out how encoding/decoding and connection switching works. If once java code uploaded by google, I can try on.

**Comment by arduinka55055** [comment]
thanks, it'll be good
